src/MergePlugin.php
tests/phpunit/MergePluginTest.php
tests/phpunit/fixtures/testRecursiveIncludes/composer.json
tests/phpunit/fixtures/testRecursiveIncludes/composer.local.2.json
tests/phpunit/fixtures/testRecursiveIncludes/composer.local.json

This enables files which were included through the merge plugin
to include other files.

Recursively process includes (fixes #15)

---

src/MergePlugin.php

Update logging to standard established upstream in composer/composer@cb336a5.
Fixes #20.

Send debug message to STDERR

---

composer.json

Change composer-plugin-api compatibility version from '1.0.0' to '^1.0'
as recommended by @Seldaek.

Update composer-plugin-api version

---

LICENSE
composer.json
src/MergePlugin.php
tests/phpunit/MergePluginTest.php

* Add Bryan Davis as author in composer.json
* Bump copyright dates to current year

Touch up credits information

---

src/MergePlugin.php
tests/phpunit/MergePluginTest.php

Only force update mode when running for an initial plugin install if no
composer.lock file was present at the time the plugin was installed.
This will prevent dirtying the composer.lock with newer versions when
`composer install` is being used to install pinned package versions from
an existing lock file.
Closes #50

Only force update mode if not locked

---

src/Merge/ExtraPackage.php
tests/phpunit/MergePluginTest.php
tests/phpunit/fixtures/testOneMergeNoConflicts/composer.local.json

Merge contents from the conflict, replace, and provides sections of
included packages.
Closes #35
Closes #51

Add merging of conflict, replace and provides sections

---

README.md

Update README to mention all merged sections

---

src/Merge/ExtraPackage.php

Composer added enhanced RootPackageInterface and RootAliasPackage
definitions in composer/composer@599ad77 that allow us to work directly
with RootPackageInterface instead of unwrapping the inner RootPackage.
The prior ExtraPackage::castRootPackage() method is renamed to
ExtraPackage::unwrapIfNeeded() and modified to only unwrap if the needed
method is missing from the root package. This backwards compatibility
will need to be retained until a stable Composer version is released.
Closes #83

Update RootPackageInterface and RootAliasPackage handling

---

README.md
src/Merge/ExtraPackage.php
src/Merge/StabilityFlags.php
src/MergePlugin.php
tests/phpunit/Merge/StabilityFlagsTest.php
tests/phpunit/MergePluginTest.php

The code complexity measurements were getting pretty ugly looking, so I took some time to clean things up.

Refactor things

---

.arcconfig
.arclint

Add Arcanist config files

---

src/Merge/ExtraPackage.php
src/Merge/StabilityFlags.php

* Eliminate an `if` by using array_intersect
* Extract smaller methods from StabilityFlags::extractAll()
* Use `max()` instead of `>` checks

Refactor to reduce cyclomatic complexity

---

src/Merge/ExtraPackage.php
src/Merge/PluginState.php
tests/phpunit/MergePluginTest.php
tests/phpunit/fixtures/testPrependRepositories/composer.json
tests/phpunit/fixtures/testPrependRepositories/composer.local.json

Add configuration option for adding or prepending repositories

---

README.md

- Add a link to Composer website
- Make the code block a json code block
- Add a link to the license file

Readme misc

---

README.md
src/Merge/ExtraPackage.php
src/Merge/PluginState.php
tests/phpunit/MergePluginTest.php
tests/phpunit/fixtures/testMergeScripts/composer.json
tests/phpunit/fixtures/testMergeScripts/composer.local.json
tests/phpunit/fixtures/testMergeScriptsConflict/composer.json
tests/phpunit/fixtures/testMergeScriptsConflict/composer.local.json
tests/phpunit/fixtures/testMergeScriptsConflictReplace/composer.json
tests/phpunit/fixtures/testMergeScriptsConflictReplace/composer.local.json

This allows the 'scripts' section of a composer.json file to be merged via the merge plugin.

Fixes #135: Adding merge-scripts option.

---

.travis.yml

Set trusty as the preferred test os.

Travis: test on trusty

---

README.md

Add some documentation instructions to resolve changes in sub-level `composer.json` files.

Readme: Add instructions to fix #96

---

.travis.yml

Test on PHP 8.0

---

src/ExtraPackage.php
src/MergePlugin.php
src/MultiConstraint.php
src/NestedArray.php
src/PluginState.php
src/StabilityFlags.php

* Use ?? operator where appropriate
* Remove unused variables
* Call static method statically
* Use import rather than fully qualified name

Minor code cleanup

---

.github/workflows/php.yml
.phan/config.php
composer.json
src/MergePlugin.php
src/MultiConstraint.php

Use phan-suppress-next-line on a couple of lines where it needs
composer 1.x code; expect phan to be tested against composer 2.x.

Setup mediawiki/mediawiki-phan-config

---

.github/workflows/CI.yaml
composer.json
tests/phpunit/LoggerTest.php
tests/phpunit/MergePluginTest.php
tests/phpunit/PluginStateTest.php
tests/phpunit/StabilityFlagsTest.php

https://github.com/wikimedia/composer-merge-plugin/issues/241

Drop support for PHP 7.2 and 7.3

---

.github/workflows/CI.yaml

https://github.com/wikimedia/composer-merge-plugin/issues/255

CI.yaml: Test on PHP 8.2
