wikimedia/composer-merge-plugin

- tests/phpunit/MergePluginTest.php
Fix #22 by adding the newly required `$devMode` parameter to the
`Composer\Installer\InstallerEvent` constructors used in testing.
> Fix InstallerEvent constructor args in tests

- src/MergePlugin.php
`Composer\Script\CommandEvent` was deprecated in composer/composer@3efed22. The
recommended signature for a script handler callback is now to use
`Composer\Script\Event` instead.
Fixes #21
> Composer\Script\CommandEvent -> Composer\Script\Event

- phpunit.xml.dist
Currently getting a deprecation warning when I run the tests
> Remove deprecated PHPUnitn strict option

- src/MergePlugin.php
- tests/phpunit/MergePluginTest.php
- tests/phpunit/fixtures/testMergedAutoload/composer.json
- tests/phpunit/fixtures/testMergedAutoload/extensions/Foo/composer.json
Fixes https://github.com/wikimedia/composer-merge-plugin/issues/18
Please note that I have only tested this automatically. It's possible I misunderstood what should happen and thus wrote an incorrect test. Manual testing on a real install before merging is advised.
> Merge in the autoload sections of merged packages

- src/MergePlugin.php
* Use Composer\Package\RootPackage type hint
* Use empty() to check arrays
* Type hint ArrayLoader::load()
* Mark debugging code ignored for coverage reports
> Fix issues reported by Scrutinizer tests

- src/MergePlugin.php
- tests/phpunit/MergePluginTest.php
"Even though it sounds a bit mad, it's not that dirty in practice." -- @Seldaek
Listen for package install events and if the installed package is our
plugin set a flag for later. When the post-install/update event fires
and the flag is set, create and run a second Composer\Installer
instance in update mode. This will allow the newly installed plugin an
opportunity to process directives in the current composer.json file.
Fixes #34
> Run update automatically when plugin is first installed

- example/composer.json
- src/MergePlugin.php
- tests/phpunit/MergePluginTest.php
- tests/phpunit/fixtures/testOneMergeNoConflicts/composer.local.json
- tests/phpunit/fixtures/testOneMergeWithConflicts/composer.local.json
Capture additional state information about autoloader dump settings and
read information from the root config so that when our plugin is
initially installed we can do a more complete job of executing a second
install cycle. Ideally we would be able to copy this and other
information from the currently executing \Composer\Installer instance
but unfortunately the plugin does not have access to it via the event
system.
Closes #41
> Better support for initial install of plugin

- README.md
- src/MergePlugin.php
- tests/phpunit/MergePluginTest.php
- tests/phpunit/fixtures/testCorrectMergeOrderOfSpecifiedFilesAndGlobFiles/a.json
- tests/phpunit/fixtures/testCorrectMergeOrderOfSpecifiedFilesAndGlobFiles/b.json
- tests/phpunit/fixtures/testCorrectMergeOrderOfSpecifiedFilesAndGlobFiles/composer.json
- tests/phpunit/fixtures/testCorrectMergeOrderOfSpecifiedFilesAndGlobFiles/glob/a-glob2.json
- tests/phpunit/fixtures/testCorrectMergeOrderOfSpecifiedFilesAndGlobFiles/glob/b-glob1.json
- tests/phpunit/fixtures/testMergeWithReplace/composer.json
- tests/phpunit/fixtures/testMergeWithReplace/composer.local.json
Introduce a new `extra.merge-plugin.replace` configuration directive
that can be used to change the default conflict resolution mechanism.
When enabled, duplicate package declarations in merged files will
overwrite the declarations made in earlier files. Files are loaded in
the order specified in `extra.merge-plugin.include` with globbed files
being loaded in alphabetical order.
This behavior can be used to replace a default stable package with a dev
or beta version of the same package for testing.
Closes #45
Supersedes #46, #44
> Add support for 'last defined package wins' conflict resolution

- src/MergePlugin.php
- tests/phpunit/MergePluginTest.php
- tests/phpunit/fixtures/testMergedAutoload/composer.json
- tests/phpunit/fixtures/testMergedAutoload/extensions/Foo/composer.json
Currently [`autoload-dev`](https://getcomposer.org/doc/04-schema.md#autoload-dev) blocks aren't merged (whereas `require-dev` are). This adds them in.
> Add autoload-dev support

- README.md
- src/MergePlugin.php
- tests/phpunit/MergePluginTest.php
- tests/phpunit/fixtures/testMergeExtra/composer.json
- tests/phpunit/fixtures/testMergeExtra/composer.local.json
- tests/phpunit/fixtures/testMergeExtraConflict/composer.json
- tests/phpunit/fixtures/testMergeExtraConflict/composer.local.json
- tests/phpunit/fixtures/testMergeExtraConflictReplace/composer.json
- tests/phpunit/fixtures/testMergeExtraConflictReplace/composer.local.json
Introduce a new `extra.merge-plugin.merge-extra` to optionally enable
merging of "extra" sections found in composer.json files. Default merge
behavior is first value wins with duplicate values triggering warnings
when `--verbose` mode is enabled. When the `replace` mode is enabled via
`extra.merge-plugin.replace: true` the merge strategy will change to
last value wins. The utility of merging "extra" sections is not well
specified and will depend on the plugins in use and the processing order
of Composer for all installed plugins.
Closes #49
Supersedes #48
> Add support for merging "extras" section

- README.md
Add an expository paragraph to the README explaining the core use case
supported by the plugin. Also clarify that "runtime" refers to
Composer's runtime and not the runtime of the managed application.
Closes #52
> Add better description to README.md

- src/Logger.php
- src/Merge/ExtraPackage.php
- src/Merge/PluginState.php
- src/MergePlugin.php
- tests/phpunit/LoggerTest.php
- tests/phpunit/Merge/PluginStateTest.php
- tests/phpunit/MergePluginTest.php
MergePlugin started out as a mostly reasonable 225 line file but has
since ballooned to 660+ lines as features have been added. Start to chip
away at this by splitting the class into 4 parts:
* Wikimedia\Composer\MergePlugin: core Composer plugin methods
* Wikimedia\Composer\Logger: Wrapper for IOInterface
* Wikimedia\Composer\Merge\ExtraPackage: Core merge logic
* Wikimedia\Composer\Merge\PluginState: Configuration and runtime state
There is probably more work to be done here, but it feels a bit cleaner.
> Split ever growing MergePlugin into more manageable chunks

- composer.json
Having a branch alias allows us to associate a semantic version number
with the development branch. This can be used by a consuming project to
follow the latest unreleased version while still retaining the ability
to prevent adoption of major/minor version breaks.
This version number should be bumped concurrently with or just before
pulling new minor version changing commits into the master branch. The
current master branch is progressing towards the 1.3.0 release milestone
so we will start with "1.3.x" as the alias. This can remain until we
start to bring in changes for the 1.4.0 release.
More details at <https://getcomposer.org/doc/articles/aliases.md>
> Add branch alias for master branch

- src/Merge/ExtraPackage.php
- tests/phpunit/MergePluginTest.php
- tests/phpunit/fixtures/testMergedAutoload/composer.json
- tests/phpunit/fixtures/testMergedAutoload/composer.local.json
- tests/phpunit/fixtures/testMergedAutoload/private/bootstrap.php
Fix require/require-dev file path computation for included configuration
files that are in the same directory as the root composer.json. Change
includes minor refactoring to eliminate pass-by-reference semantics and
improve method naming.
Closes #64
> Compute proper autoload paths

- README.md
- src/MergePlugin.php
* Add sub-section headings for configuration settings
* Fix a few awkward sentences
* Swap the "replace" and "merge-extra" configuration settings
explanations for better flow
* Consistent whitespace
* Update MergePlugin doc comment to reflect current functionality
> Update README and doc comments

- src/Logger.php
- src/Merge/ExtraPackage.php
- src/Merge/PluginState.php
- src/MergePlugin.php
- tests/phpunit/MergePluginTest.php
- tests/phpunit/fixtures/testHasBranchAlias/composer.json
- tests/phpunit/fixtures/testHasBranchAlias/composer.local.json
When the top level Package includes an "extra.branch-alias" directive
Composer wraps the normal `RootPackage` in a `RootAliasPackage`. This is
done to allow the `RootAliasPackage` to modify the version information
in "require", "require-dev", "conflict", "provide" and "replace" sections
of the package. Unfortunately `RootAliasPackage` does not implement the
complete public API of `RootPackage` so we need to apply special checks
for its presence.
Previously we tried to handle this by immediately unwrapping the aliased
root package and making all operations use it directly. This
unfortunately doesn't work as internally Composer caches data for the
collections that can be modified by the alias in the `RootAliasPackage`
at construction time. This prevents our changes to those collections
from …
> Handle RootAliasPackage as correctly as we can

- src/Logger.php
- src/Merge/ExtraPackage.php
- src/MergePlugin.php
- tests/phpunit/LoggerTest.php
Only log duplicate files in VeryVerbose mode (`-vv`) and report the
files as "already merged" rather than "skipping duplicate" to reduce
confusion by end users.
Closes #66
> Adjust logging of duplicate files

- .scrutinizer.yml
- .travis.yml
Update CI control files to exclude PHP7 and HHVM from coverage reporting
and adjust the time a job is expected to take and how many will report
coverage data.
> Updating Travis CI and Scrutinizer yaml files.

- composer.json
- tests/phpunit/LoggerTest.php
- tests/phpunit/Merge/PluginStateTest.php
- tests/phpunit/MergePluginTest.php
$ vendor/bin/phpunit --verbose
PHPUnit 5.0.5 by Sebastian Bergmann and contributors.
Runtime:       PHP 5.6.14 with Xdebug 2.3.3
Configuration: /work/GIT/composer-merge-plugin/phpunit.xml.dist
......................                                            22 / 22 (100%)
Time: 232 ms, Memory: 17.75Mb
OK (22 tests, 223 assertions)
> allow modern PHPUnit

- src/Merge/ExtraPackage.php
- tests/phpunit/MergePluginTest.php
- tests/phpunit/fixtures/testMergedStabilityFlagsRespectsMinimumStability/composer.json
- tests/phpunit/fixtures/testMergedStabilityFlagsRespectsMinimumStability/composer.local.json
- tests/phpunit/fixtures/testUpdateStabilityFlags/composer.local.json
Implement stability flag extraction that properly follows the logic of
RootPackageLoader::extractStabilityFlags.
The prior implementation introduced in #10 (0a54f7f) ignored the
complexity of extracting explicit stability flags (eg '@dev') and the
possibility of needing to strip aliases. Even worse it introduced a test
that really didn't test anything at all. What the heck was I thinking?
Closes #71
> Fix stability flag extraction

- README.md
- src/Merge/ExtraPackage.php
- src/Merge/PluginState.php
- tests/phpunit/MergePluginTest.php
- tests/phpunit/fixtures/testMergeDevFalse/composer.json
- tests/phpunit/fixtures/testMergeDevFalse/composer.local.json
Add a new "merge-dev" configuration option that allows the root package
to disable processing of "autoload-dev" and "require-dev" sections of
merged files.
Closes #85
> Allow merging of *-dev sections to be disabled

- README.md
- src/Merge/ExtraPackage.php
- src/Merge/MissingFileException.php
- src/Merge/PluginState.php
- src/MergePlugin.php
- tests/phpunit/MergePluginTest.php
- tests/phpunit/fixtures/testMissingRequireThrowsException/composer.json
- tests/phpunit/fixtures/testRequire/composer.json
- tests/phpunit/fixtures/testRequire/composer.local.json
The `require` setting functions the same as the `include` setting but
raises an exception when any pattern supplied fails to match any files.
Closes #37
> Add support for required files

- src/Merge/ExtraPackage.php
- tests/phpunit/MergePluginTest.php
Summary:
Composer was changed in https://github.com/composer/composer/pull/4542
to provide a full interface for RootAliasPackage so that we no longer
need to try and unwrap the aliased package. Update the unit tests to
detect the Composer version in use by looking for
a RootAliasPackage::setRepositories() method and adjust mock
expectations accordingly.
Test Plan:
Run `composer test` with old version of Composer (eg 1.0.0-alpha10) and
newer version (eg 1.0.0-alpha11).
Reviewers: Legoktm
Differential Revision: https://phabricator.wikimedia.org/D63
> Fix unit tests for Composer upstream changes

- .travis.yml
- src/Merge/ExtraPackage.php
- tests/phpunit/MergePluginTest.php
- tests/phpunit/fixtures/testSelfVersionNoRootVersion/composer.json
- tests/phpunit/fixtures/testSelfVersionNoRootVersion/composer.local.json
``foo/baz`` should resolve to ``~8.0`` because the root composer.json requires ``~8.0.``
> Resolve the self.version contraint through packages from the root package

- src/Merge/ExtraPackage.php
- tests/phpunit/MergePluginTest.php
- tests/phpunit/fixtures/testVersionConstraintWithRevision/composer.json
- tests/phpunit/fixtures/testVersionConstraintWithRevision/composer.local.json
> Add source reference information for merged packages

- .travis.yml
Follow up to 1000cdb that disables the TLS handling for Composer before
trying to do anything else. The base Composer version at Travis is now
new enough that self-update fails on 5.3 when TLS is left enabled.
> TravisCI: Disable Composer TLS for PHP 5.3

- .travis.yml
I forced this through without understanding why Travis wasn't reporting
a build result. I totally thought about YAML validation when I wrote the
prior patch too, but then I forgot to actually verify that `- [...] ...`
was valid (it's not really). You'd think that I'd know better.
> TravisCI: fix YAML syntax errors

- README.md
- composer.json
- src/Merge/ExtraPackage.php
- src/Merge/PluginState.php
- tests/phpunit/MergePluginTest.php
- tests/phpunit/fixtures/testPrependRepositories/composer.json
Follow up to 9645a93 that makes the use of
RepositoryManager::prependRepository() the default behavior for all
repository merges. This ensures that epos added by the included/required
config files to have a higher priority than the repos added in the root
composer.json and most importantly higher than the default packagist
repo.
Closes #95
> Always prepend repositories

- src/Merge/PluginState.php
- src/MergePlugin.php
Composer determines if a given package is a dev mode dependency by
running a solver with dev mode disabled and diffing the result against
the full solver run. This causes every run to two emit
`InstallerEvents::PRE_DEPENDENCIES_SOLVING` events: one with dev mode
enabled and one without. Previously we were using the global dev mode
state set by the main install/update/dump event for both calls. This led
Composer to believe that all conflicting pacakges processed by
composer-merge-plugin were non-dev requirements and an unexpected
composer.lock state for later `composer install --no-dev` executions.
Closes #113
> Use dev mode flag from event in onDependencySolve callback

- src/MergePlugin.php
Attempt to take action before other Composer plugins that may be in use
by registering our callbacks using the highest possible priority.
Closes #99
> Register callbacks with highest priority

- README.md
Add a note about the quirk of `merge-scripts` and custom commands not
working when called using shortcut syntax from the command line.
Follow up to 1b37cd3.
> Document lack of custom command shortcuts

- README.md
Replaced link and image to show status of GitHub Actions instead of Travis CI.
Amends b9137cbf90d2776f2d70290119c0692fd032fbc6
> Update "Build Status" button in README

- .github/workflows/php.yml
- README.md
- composer.json
- example/composer.json
- src/Logger.php
- src/Merge/ExtraPackage.php
- src/Merge/MultiConstraint.php
- src/Merge/PluginState.php
- src/MergePlugin.php
- tests/phpunit/MergePluginTest.php
Latest Update 2021-01-25 14:25 EST
**Notes**:
1. Avoid unnecessary issue bumping. Please test this pull request and report issues or approve working state.  
See [comment](https://github.com/wikimedia/composer-merge-plugin/pull/189#issuecomment-731199112).
2. Stability of this pull request's changeset needs additional testing from the community, such as unintentional updates upon requiring this plugin.  
See [comment](https://github.com/wikimedia/composer-merge-plugin/pull/189#issuecomment-728452368).
3. Project is stuck in the process of transferring ownership to a new team within the Wikimedia Foundation.  
See [comment](https://github.com/wikimedia/composer-merge-plugin/pull/189#issuecomment-728375965).
4. Since v1.4 of the plugin does not support Composer v2, the plugin is ignored …
> Add support for Composer v2

- composer.json
- src/ExtraPackage.php
- src/Logger.php
- src/MergePlugin.php
- src/MissingFileException.php
- src/MultiConstraint.php
- src/NestedArray.php
- src/PluginState.php
- src/StabilityFlags.php
- tests/phpunit/LoggerTest.php
- tests/phpunit/MergePluginTest.php
- tests/phpunit/NestedArrayTest.php
- tests/phpunit/PluginStateTest.php
- tests/phpunit/StabilityFlagsTest.php
Composer would try to load two versions of the same plugin, by reading the main plugin file and rewriting the class name. But this doesn't work if the plugin has multiple classes. It tries to run the new plugin class with old helper classes.
So:
* Move all classes to Wikimedia\Composer\Merge\V2. This includes classes that were previously in the parent namespace.
* Clean up unused "use" statements.
Note that the namespace version number will have to be incremented every time there is an internal interface change.
Closes #205
> Work around Composer multi-version loading hack using a "V2" namespace

- tests/phpunit/StabilityFlagsTest.php
Closes https://github.com/wikimedia/composer-merge-plugin/issues/208
> FixStabilityFlagsTest::testLowestWins() to use data provider

- .github/workflows/CI.yaml
- README.md
GitHub's base images have all the modern php versions pre-installed (as php7.1, php7.2, etc., Debian-style), including composer, xdebug and most anything else we need.
Use that directly, instead of various complex third-party docker and [Webpack-compiled Node.js scripts](https://github.com/shivammathur/setup-php/blob/2.10.0/dist/index.js) (?) to install other novel PHP binaries, and run-time downloading composer, with each step running in a different container with different packages present.
Runtime from last build before this commit
<https://github.com/wikimedia/composer-merge-plugin/actions/runs/638619206>
> Test PHP 7.2 1m 59s   |
> Test PHP 7.3 1m 42s   | =>  ocular-push 1m 35s
> Test PHP 7.4 1m 17s   |
> Test PHP 8.0 1m 5s    |
Runtime from one the builds for this commit: …
> build: Use php and composer from debian packages

- src/ExtraPackage.php
- tests/phpunit/MergePluginTest.php
- tests/phpunit/fixtures/testRecursiveIncludesWithSubDirectory/composer.json
- tests/phpunit/fixtures/testRecursiveIncludesWithSubDirectory/subdirectory/composer.local.2.json
- tests/phpunit/fixtures/testRecursiveIncludesWithSubDirectory/subdirectory/composer.local.json
- tests/phpunit/fixtures/testRecursivePathRepositoriesWithSubDirectory/composer.json
- tests/phpunit/fixtures/testRecursivePathRepositoriesWithSubDirectory/subdirectory/composer.local.2.json
- tests/phpunit/fixtures/testRecursivePathRepositoriesWithSubDirectory/subdirectory/composer.local.json
- tests/phpunit/fixtures/testRecursiveRequires/composer.json
- tests/phpunit/fixtures/testRecursiveRequires/composer.local.2.json
- tests/phpunit/fixtures/testRecursiveRequires/composer.local.json
- tests/phpunit/fixtures/testRecursiveRequiresWithSubDirectory/composer.json
- tests/phpunit/fixtures/testRecursiveRequiresWithSubDirectory/subdirectory/composer.local.2.json
- tests/phpunit/fixtures/testRecursiveRequiresWithSubDirectory/subdirectory/composer.local.json
This affects the fields:
- "required",
- "include", and
- "path repository"
Added test cases for each.
Re-based and updated version of #160.
Fixes #161.
> Re-write relative paths for fields when recursing
